apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.secrets }}
        {{- range $key, $value := .Values.secrets }}
        {{- if $value }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Chart.Name }}-secrets
              key: {{ $key }}
        {{- end }}
        {{- end }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthcheck.path }}
            port: 3000
            scheme: HTTP
          initialDelaySeconds: {{ .Values.healthcheck.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.liveness.timeoutSeconds }}
          successThreshold: {{ .Values.healthcheck.liveness.successThreshold }}
          failureThreshold: {{ .Values.healthcheck.liveness.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthcheck.path }}
            port: 3000
            scheme: HTTP
          initialDelaySeconds: {{ .Values.healthcheck.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.readiness.timeoutSeconds }}
          successThreshold: {{ .Values.healthcheck.readiness.successThreshold }}
          failureThreshold: {{ .Values.healthcheck.readiness.failureThreshold }}
        startupProbe:
          httpGet:
            path: {{ .Values.healthcheck.path }}
            port: 3000
            scheme: HTTP
          initialDelaySeconds: {{ .Values.healthcheck.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.startup.timeoutSeconds }}
          successThreshold: {{ .Values.healthcheck.startup.successThreshold }}
          failureThreshold: {{ .Values.healthcheck.startup.failureThreshold }}