{{- if .Values.aws.secretsManager.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-supabase-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Chart.Name }}-aws-secrets
    kind: SecretStore
  target:
    name: {{ .Chart.Name }}-aws-secrets
    type: Opaque
  data:
  - secretKey: SUPABASE_SERVICE_ROLE_KEY
    remoteRef:
      key: {{ .Values.aws.secretsManager.supabaseSecretName }}
{{- end }}
