{{- if .Values.aws.secretsManager.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Chart.Name }}-aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
{{- end }}