apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  {{- if .Values.aws.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.serviceAccount.roleArn }}
  {{- end }}
