# Production values for mnm-prompts

# Namespace specification
namespace: mnm-prompts

image:
  repository: 767624311656.dkr.ecr.eu-west-1.amazonaws.com/mnm-prompts
  tag: latest
  pullPolicy: Always

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3000
  annotations: {}

ingress:
  enabled: true  # Set to false to disable ingress
  host: prompts.mnm.dev
  certificateArn: ""
  
# Environment variables
env:
  NODE_ENV: production
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_TELEMETRY_DISABLED: "1"    # Add your public environment variables here
  NEXT_PUBLIC_SITE_URL: "https://prompts.mnm.dev"
  # DATABASE_URL should be set via AWS Secrets Manager
  # For Supabase, format: postgresql://postgres:[password]@[host]:6543/postgres?pgbouncer=true

# Health check configuration
healthcheck:
  path: /api/healthcheck
  
  # Liveness probe - restarts container if failing
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  
  # Readiness probe - removes from service if failing
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3
  
  # Startup probe - protects slow starting containers
  startup:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 30

# Resource limits for production
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Horizontal Pod Autoscaler configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 2


aws:
  region: eu-west-1
  secretsManager:
    enabled: true
    appSecrets: mnm-prompts-prod-secrets
  serviceAccount:
    roleArn: arn:aws:iam::767624311656:role/mnm-prompts-secrets-role 


persistence:
  enabled: true
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  mountPath: /data
  subPath: ""